build-job:
  stage: build
  script:
    - apt update
    - apt install -y build-essential wget
    - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
    - chmod +x bazelisk-linux-amd64
    - mv bazelisk-linux-amd64 /usr/bin/bazel
    - bazel run //exploration/winding/benches:plane2d_from_points
    - bazel run //exploration/winding/benches:plane2d_intersection